### ISSUE TITLE
Some questions about logic task

### ISSUE THREAD

**Issue by xcc658228** [siyuyuan/evoagent#2]
Thank for your work.
When I am in the process of running the logic issue, I am unable to run it successfully.

NameError: name 'input_data' is not defined

This variable is set in the writing task, but not in the logic task.

**Comment by xcc658228** [comment]
Possible omission: input_data = data[‘inputs’]

**Comment by siyuyuan** [comment]
@xcc658228 Thank you so much for pointing out this type! I have corrected this:)
