### ISSUE TITLE
some questions about the code of the evoagent 

### ISSUE THREAD

**Issue by xcc658228** [siyuyuan/evoagent#3]
In the process of replicating this paper, I found that the code provided in this paper did not seem to contain evoagent. I wonder if it was not uploaded, or I was not careful enough.
     At the same time, the readme actually lacks instructions for selecting methods used by the model, but the readme is really only set for collaborate methods.

**Comment by siyuyuan** [comment]
Thanks for your asking! We have updated the code to the newest version! 
`--method evoagent` is used to execute evoagent.
For the selection step, you can use the following code to execute:

```
flag = 0
while True:
    prompt = meta_agent_prompt.format(question=question, answer=answer, description='\n-'.join(description_ls))
    messages = message_construction(model_name, prompt)
    description = evaluator_construction(messages, model_name, question, data_type)

    prompt = check_agent_prompt.format(question=question, description_ls='\n-'.join(description_ls), description=description)
    messages = message_construction(model_name, prompt)
    check_result = evaluator_construction(messages, model_name, question, data_type)
    print(check_result)
    if 'discard' not in check_result.lower() or flag > 3:
        description_ls.append(description)
        break
    flag += 1
```
